{"name": "测试错误账号、错误密码情况下的登录", "status": "passed", "description": "登录失败：测试错误账号、错误密码登录", "start": 1749803175986, "stop": 1749803181586, "uuid": "4a98592a-05a5-4879-8e52-ee5b83989a8e", "historyId": "a85432e1f09ae03b641ca9cf8de7a5a5", "testCaseId": "a85432e1f09ae03b641ca9cf8de7a5a5", "fullName": "test_dir.Login.test_003_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录失败"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "17212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_003_loginfail"}]}