{"name": "test_login_fail_case", "status": "passed", "description": "登录失败：测试正确账号、错误密码登录", "attachments": [{"name": "stdout", "source": "fbbe1621-346f-49a3-880d-2b2dc45c5f58-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4d17d3b6-f7a4-4a6e-99e0-edbd94e5f3e4-attachment.txt", "type": "text/plain"}], "start": 1749453672196, "stop": 1749453679590, "uuid": "d068104c-73a0-4533-a2a3-36d8dbeb3699", "historyId": "9bafb470a3f5b2bc06ae6138b0479d4f", "testCaseId": "9bafb470a3f5b2bc06ae6138b0479d4f", "fullName": "test_dir.Login.test_001_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录功能"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "2844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_001_loginfail"}]}