{"name": "测试错误账号、错误密码情况下的登录", "status": "passed", "description": "登录失败：测试错误账号、错误密码登录", "attachments": [{"name": "stderr", "source": "051a9564-0aa6-4971-a27d-171e0a659513-attachment.txt", "type": "text/plain"}], "start": 1749455103102, "stop": 1749455108017, "uuid": "17e0c55a-4117-422b-9983-a153c86c5d36", "historyId": "a85432e1f09ae03b641ca9cf8de7a5a5", "testCaseId": "a85432e1f09ae03b641ca9cf8de7a5a5", "fullName": "test_dir.Login.test_003_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录失败"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "6696-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_003_loginfail"}]}