{"name": "test_login_fail_case", "status": "passed", "description": "登录失败：测试正确账号、错误密码登录", "attachments": [{"name": "stdout", "source": "efb9f66f-fae0-44d4-9811-09a39915e425-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e151c9a2-d0ca-43e6-8c79-7386ada89d3b-attachment.txt", "type": "text/plain"}], "start": 1749454555695, "stop": 1749454564449, "uuid": "0537a5ed-99f0-48a0-bd32-2786496805cc", "historyId": "9bafb470a3f5b2bc06ae6138b0479d4f", "testCaseId": "9bafb470a3f5b2bc06ae6138b0479d4f", "fullName": "test_dir.Login.test_001_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录功能"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "8868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_001_loginfail"}]}