{"name": "测试错误账号、错误密码情况下的登录", "status": "passed", "description": "登录失败：测试错误账号、错误密码登录", "start": 1749457224506, "stop": 1749457229427, "uuid": "bafa541f-704f-4937-8bcc-8a822a2594ac", "historyId": "a85432e1f09ae03b641ca9cf8de7a5a5", "testCaseId": "a85432e1f09ae03b641ca9cf8de7a5a5", "fullName": "test_dir.Login.test_003_loginfail.TestLoginFail#test_login_fail_case", "labels": [{"name": "suite", "value": "登录"}, {"name": "feature", "value": "登录失败"}, {"name": "parentSuite", "value": "test_dir.Login"}, {"name": "subSuite", "value": "TestLoginFail"}, {"name": "host", "value": "DESKTOP-9JRI8LF"}, {"name": "thread", "value": "20876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.Login.test_003_loginfail"}]}